package com.squaredcandy.lunar.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0062A1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D35)
//val md_theme_light_secondary = Color(0xFF006A6A)
val md_theme_light_secondary = Color(0xFF00629E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCFE5FF)
//val md_theme_light_secondaryContainer = Color(0xFF6FF7F6)
val md_theme_light_onSecondaryContainer = Color(0xFF001D34)
//val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF7B4997)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF5D9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF30004A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9CCAFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0062A1)

val md_theme_dark_primary = Color(0xFF9CCAFF)
val md_theme_dark_onPrimary = Color(0xFF003257)
val md_theme_dark_primaryContainer = Color(0xFF00497B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_secondary = Color(0xFF99CBFF)
//val md_theme_dark_secondary = Color(0xFF4CDADA)
val md_theme_dark_onSecondary = Color(0xFF003355)
//val md_theme_dark_onSecondary = Color(0xFF003737)
val md_theme_dark_secondaryContainer = Color(0xFF004A78)
//val md_theme_dark_secondaryContainer = Color(0xFF004F4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE5FF)
//val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F6)
val md_theme_dark_tertiary = Color(0xFFE6B4FF)
val md_theme_dark_onTertiary = Color(0xFF491765)
val md_theme_dark_tertiaryContainer = Color(0xFF62317D)
val md_theme_dark_onTertiaryContainer = Color(0xFFF5D9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0062A1)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9CCAFF)

// Source
private val seed = Color(0xFF25A0FE)
private val Red = Color(0xFFA02929)
private val Green = Color(0xFF619647)
private val Yellow = Color(0xFFFE9B00)
private val Blue = Color(0xFF6897C6)
private val Magenta = Color(0xFF664975)
private val Cyan = Color(0xFF00B1B1)
private val BrightRed = Color(0xFFC70202)
private val BrightGreen = Color(0xFF4CD20C)
private val BrightYellow = Color(0xFFFADF1B)
private val BrightBlue = Color(0xFF25A0FE)
private val BrightMagenta = Color(0xFFB029F7)
private val BrightCyan = Color(0xFF30F7F7)

// Red
val light_red = Color(0xFFAC3231)
val light_onred = Color(0xFFFFFFFF)
val light_redContainer = Color(0xFFFFDAD7)
val light_onredContainer = Color(0xFF410004)
val dark_red = Color(0xFFFFB3AD)
val dark_onred = Color(0xFF68000A)
val dark_redContainer = Color(0xFF8B191C)
val dark_onredContainer = Color(0xFFFFDAD7)

// Green
val light_green = Color(0xFF376A20)
val light_ongreen = Color(0xFFFFFFFF)
val light_greenContainer = Color(0xFFB7F397)
val light_ongreenContainer = Color(0xFF072100)
val dark_green = Color(0xFF9CD67E)
val dark_ongreen = Color(0xFF103800)
val dark_greenContainer = Color(0xFF1F5107)
val dark_ongreenContainer = Color(0xFFB7F397)

// Yellow
val light_yellow = Color(0xFF895100)
val light_onyellow = Color(0xFFFFFFFF)
val light_yellowContainer = Color(0xFFFFDCBC)
val light_onyellowContainer = Color(0xFF2C1700)
val dark_yellow = Color(0xFFFFB86B)
val dark_onyellow = Color(0xFF492900)
val dark_yellowContainer = Color(0xFF683D00)
val dark_onyellowContainer = Color(0xFFFFDCBC)

// Blue
val light_blue = Color(0xFF00629E)
val light_onblue = Color(0xFFFFFFFF)
val light_blueContainer = Color(0xFFCFE5FF)
val light_onblueContainer = Color(0xFF001D34)
val dark_blue = Color(0xFF99CBFF)
val dark_onblue = Color(0xFF003355)
val dark_blueContainer = Color(0xFF004A78)
val dark_onblueContainer = Color(0xFFCFE5FF)

// Magenta
val light_magenta = Color(0xFF7B4997)
val light_onmagenta = Color(0xFFFFFFFF)
val light_magentaContainer = Color(0xFFF5D9FF)
val light_onmagentaContainer = Color(0xFF30004A)
val dark_magenta = Color(0xFFE6B4FF)
val dark_onmagenta = Color(0xFF491765)
val dark_magentaContainer = Color(0xFF62317D)
val dark_onmagentaContainer = Color(0xFFF5D9FF)

// Cyan
val light_cyan = Color(0xFF006A6A)
val light_oncyan = Color(0xFFFFFFFF)
val light_cyanContainer = Color(0xFF6FF7F6)
val light_oncyanContainer = Color(0xFF002020)
val dark_cyan = Color(0xFF4CDADA)
val dark_oncyan = Color(0xFF003737)
val dark_cyanContainer = Color(0xFF004F4F)
val dark_oncyanContainer = Color(0xFF6FF7F6)

// Bright Red
val light_bright_red = Color(0xFFC00001)
val light_onbright_red = Color(0xFFFFFFFF)
val light_bright_redContainer = Color(0xFFFFDAD4)
val light_onbright_redContainer = Color(0xFF410000)
val dark_bright_red = Color(0xFFFFB4A8)
val dark_onbright_red = Color(0xFF690000)
val dark_bright_redContainer = Color(0xFF930000)
val dark_onbright_redContainer = Color(0xFFFFDAD4)

// Bright Green
val light_bright_green = Color(0xFF226D00)
val light_onbright_green = Color(0xFFFFFFFF)
val light_bright_greenContainer = Color(0xFF7CFF49)
val light_onbright_greenContainer = Color(0xFF052100)
val dark_bright_green = Color(0xFF5CE225)
val dark_onbright_green = Color(0xFF0E3900)
val dark_bright_greenContainer = Color(0xFF185200)
val dark_onbright_greenContainer = Color(0xFF7CFF49)

// Bright Yellow
val light_bright_yellow = Color(0xFF6B5F00)
val light_onbright_yellow = Color(0xFFFFFFFF)
val light_bright_yellowContainer = Color(0xFFFEE322)
val light_onbright_yellowContainer = Color(0xFF201C00)
val dark_bright_yellow = Color(0xFFE0C700)
val dark_onbright_yellow = Color(0xFF383100)
val dark_bright_yellowContainer = Color(0xFF514700)
val dark_onbright_yellowContainer = Color(0xFFFEE322)

// Bright Blue
val light_bright_blue = Color(0xFF0062A1)
val light_onbright_blue = Color(0xFFFFFFFF)
val light_bright_blueContainer = Color(0xFFD0E4FF)
val light_onbright_blueContainer = Color(0xFF001D35)
val dark_bright_blue = Color(0xFF9CCAFF)
val dark_onbright_blue = Color(0xFF003257)
val dark_bright_blueContainer = Color(0xFF00497B)
val dark_onbright_blueContainer = Color(0xFFD0E4FF)

// Bright Magenta
val light_bright_magenta = Color(0xFF9400D7)
val light_onbright_magenta = Color(0xFFFFFFFF)
val light_bright_magentaContainer = Color(0xFFF5D9FF)
val light_onbright_magentaContainer = Color(0xFF30004A)
val dark_bright_magenta = Color(0xFFE7B4FF)
val dark_onbright_magenta = Color(0xFF500076)
val dark_bright_magentaContainer = Color(0xFF7100A5)
val dark_onbright_magentaContainer = Color(0xFFF5D9FF)

// Bright Cyan
val light_bright_cyan = Color(0xFF006A6A)
val light_onbright_cyan = Color(0xFFFFFFFF)
val light_bright_cyanContainer = Color(0xFF37FAFA)
val light_onbright_cyanContainer = Color(0xFF002020)
val dark_bright_cyan = Color(0xFF00DDDD)
val dark_onbright_cyan = Color(0xFF003737)
val dark_bright_cyanContainer = Color(0xFF004F50)
val dark_onbright_cyanContainer = Color(0xFF37FAFA)
