package com.squaredcandy.lunar.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0062A1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D35)
val md_theme_light_secondary = Color(0xFF00629E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D34)
val md_theme_light_tertiary = Color(0xFF7B4997)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF5D9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF30004A)
val md_theme_light_error = Color(0xFFAC3231)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD7)
val md_theme_light_onErrorContainer = Color(0xFF410004)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFF8FAFA)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inversePrimary = Color(0xFF9CCAFF)
val md_theme_light_surfaceTint = Color(0xFF0062A1)
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9CCAFF)
val md_theme_dark_onPrimary = Color(0xFF003257)
val md_theme_dark_primaryContainer = Color(0xFF00497B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_secondary = Color(0xFF99CBFF)
val md_theme_dark_onSecondary = Color(0xFF003355)
val md_theme_dark_secondaryContainer = Color(0xFF004A78)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_tertiary = Color(0xFFE6B4FF)
val md_theme_dark_onTertiary = Color(0xFF491765)
val md_theme_dark_tertiaryContainer = Color(0xFF62317D)
val md_theme_dark_onTertiaryContainer = Color(0xFFF5D9FF)
val md_theme_dark_error = Color(0xFFFFB3AD)
val md_theme_dark_onError = Color(0xFF68000A)
val md_theme_dark_errorContainer = Color(0xFF8B191C)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD7)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF101415)
val md_theme_dark_onSurface = Color(0xFFC4C7C7)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inversePrimary = Color(0xFF0062A1)
val md_theme_dark_surfaceTint = Color(0xFF9CCAFF)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)

// Source
private val seed = Color(0xFF25A0FE)
private val Red = Color(0xFFA02929)
private val Green = Color(0xFF619647)
private val Yellow = Color(0xFFFE9B00)
private val Blue = Color(0xFF6897C6)
private val Magenta = Color(0xFF664975)
private val Cyan = Color(0xFF00B1B1)
private val BrightRed = Color(0xFFC70202)
private val BrightGreen = Color(0xFF4CD20C)
private val BrightYellow = Color(0xFFFADF1B)
private val BrightBlue = Color(0xFF25A0FE)
private val BrightMagenta = Color(0xFFB029F7)
private val BrightCyan = Color(0xFF30F7F7)

// Red
val light_Red = Color(0xFFAC3231)
val light_onRed = Color(0xFFFFFFFF)
val light_RedContainer = Color(0xFFFFDAD7)
val light_onRedContainer = Color(0xFF410004)
val dark_Red = Color(0xFFFFB3AD)
val dark_onRed = Color(0xFF68000A)
val dark_RedContainer = Color(0xFF8B191C)
val dark_onRedContainer = Color(0xFFFFDAD7)

// Green
val light_Green = Color(0xFF376A20)
val light_onGreen = Color(0xFFFFFFFF)
val light_GreenContainer = Color(0xFFB7F397)
val light_onGreenContainer = Color(0xFF072100)
val dark_Green = Color(0xFF9CD67E)
val dark_onGreen = Color(0xFF103800)
val dark_GreenContainer = Color(0xFF1F5107)
val dark_onGreenContainer = Color(0xFFB7F397)

// Yellow
val light_Yellow = Color(0xFF895100)
val light_onYellow = Color(0xFFFFFFFF)
val light_YellowContainer = Color(0xFFFFDCBC)
val light_onYellowContainer = Color(0xFF2C1700)
val dark_Yellow = Color(0xFFFFB86B)
val dark_onYellow = Color(0xFF492900)
val dark_YellowContainer = Color(0xFF683D00)
val dark_onYellowContainer = Color(0xFFFFDCBC)

// Blue
val light_Blue = Color(0xFF00629E)
val light_onBlue = Color(0xFFFFFFFF)
val light_BlueContainer = Color(0xFFCFE5FF)
val light_onBlueContainer = Color(0xFF001D34)
val dark_Blue = Color(0xFF99CBFF)
val dark_onBlue = Color(0xFF003355)
val dark_BlueContainer = Color(0xFF004A78)
val dark_onBlueContainer = Color(0xFFCFE5FF)

// Magenta
val light_Magenta = Color(0xFF7B4997)
val light_onMagenta = Color(0xFFFFFFFF)
val light_MagentaContainer = Color(0xFFF5D9FF)
val light_onMagentaContainer = Color(0xFF30004A)
val dark_Magenta = Color(0xFFE6B4FF)
val dark_onMagenta = Color(0xFF491765)
val dark_MagentaContainer = Color(0xFF62317D)
val dark_onMagentaContainer = Color(0xFFF5D9FF)

// Cyan
val light_Cyan = Color(0xFF006A6A)
val light_onCyan = Color(0xFFFFFFFF)
val light_CyanContainer = Color(0xFF6FF7F6)
val light_onCyanContainer = Color(0xFF002020)
val dark_Cyan = Color(0xFF4CDADA)
val dark_onCyan = Color(0xFF003737)
val dark_CyanContainer = Color(0xFF004F4F)
val dark_onCyanContainer = Color(0xFF6FF7F6)

// Bright Red
val light_BrightRed = Color(0xFFC00001)
val light_onBrightRed = Color(0xFFFFFFFF)
val light_BrightRedContainer = Color(0xFFFFDAD4)
val light_onBrightRedContainer = Color(0xFF410000)
val dark_BrightRed = Color(0xFFFFB4A8)
val dark_onBrightRed = Color(0xFF690000)
val dark_BrightRedContainer = Color(0xFF930000)
val dark_onBrightRedContainer = Color(0xFFFFDAD4)

// Bright Green
val light_BrightGreen = Color(0xFF226D00)
val light_onBrightGreen = Color(0xFFFFFFFF)
val light_BrightGreenContainer = Color(0xFF7CFF49)
val light_onBrightGreenContainer = Color(0xFF052100)
val dark_BrightGreen = Color(0xFF5CE225)
val dark_onBrightGreen = Color(0xFF0E3900)
val dark_BrightGreenContainer = Color(0xFF185200)
val dark_onBrightGreenContainer = Color(0xFF7CFF49)

// Bright Yellow
val light_BrightYellow = Color(0xFF6B5F00)
val light_onBrightYellow = Color(0xFFFFFFFF)
val light_BrightYellowContainer = Color(0xFFFEE322)
val light_onBrightYellowContainer = Color(0xFF201C00)
val dark_BrightYellow = Color(0xFFE0C700)
val dark_onBrightYellow = Color(0xFF383100)
val dark_BrightYellowContainer = Color(0xFF514700)
val dark_onBrightYellowContainer = Color(0xFFFEE322)

// Bright Blue
val light_BrightBlue = Color(0xFF0062A1)
val light_onBrightBlue = Color(0xFFFFFFFF)
val light_BrightBlueContainer = Color(0xFFD0E4FF)
val light_onBrightBlueContainer = Color(0xFF001D35)
val dark_BrightBlue = Color(0xFF9CCAFF)
val dark_onBrightBlue = Color(0xFF003257)
val dark_BrightBlueContainer = Color(0xFF00497B)
val dark_onBrightBlueContainer = Color(0xFFD0E4FF)

// Bright Magenta
val light_BrightMagenta = Color(0xFF9400D7)
val light_onBrightMagenta = Color(0xFFFFFFFF)
val light_BrightMagentaContainer = Color(0xFFF5D9FF)
val light_onBrightMagentaContainer = Color(0xFF30004A)
val dark_BrightMagenta = Color(0xFFE7B4FF)
val dark_onBrightMagenta = Color(0xFF500076)
val dark_BrightMagentaContainer = Color(0xFF7100A5)
val dark_onBrightMagentaContainer = Color(0xFFF5D9FF)

// Bright Cyan
val light_BrightCyan = Color(0xFF006A6A)
val light_onBrightCyan = Color(0xFFFFFFFF)
val light_BrightCyanContainer = Color(0xFF37FAFA)
val light_onBrightCyanContainer = Color(0xFF002020)
val dark_BrightCyan = Color(0xFF00DDDD)
val dark_onBrightCyan = Color(0xFF003737)
val dark_BrightCyanContainer = Color(0xFF004F50)
val dark_onBrightCyanContainer = Color(0xFF37FAFA)
